[project_setting]
platform_name = IAP Platform
platform_slug = iap

[frontend_setting]
cache_days = 90
show_pic = True

[backend_setting]
cache_days = 90
version = v1

[LLM]
# 定義 llm 全局變量
# taide/Llama3-TAIDE-LX-8B-Chat-Alpha1
# MediaTek-Research/Breeze-7B-Instruct-v0_1
# HuggingFaceH4/zephyr-7b-alpha
# HuggingFaceH4/zephyr-7b-beta
# MediaTek-Research/Breeze-7B-Instruct-v1_0(recommend)
# MediaTek-Research/Breeze-7B-32k-Instruct-v1_0
# Qwen/Qwen1.5-7B-Chat
# Pan`LLMCommunity/panda-index-large-zh
# gpt-3.5-turbo(recommend)
# gpt-4o-mini
; utrobinmv/t5_translate_en_ru_zh_large_1024_v2 (翻譯)
# mistralai/Mathstral-7B-v0.1
; MediaTek-Research/Breeze-3B-Instruct
# MediaTek-Research/Breeze-7B-FC-v1_0
hf_token = hf_REDACTED
time_out_second = 120

[slack]
S_URL_OTHERS = https://hooks.slack.com/services/REDACTED
S_URL_PROD_ERROR = https://hooks.slack.com/services/REDACTED

[chat_setting]
enable=True
cloud=True
model=gpt-4o-mini
temperature= 0.7
top_k= 50
top_p= 0.95
do_sample=True

[pd_instr_setting]
enable= False
cloud = False
model = deepseek-r1:7b
temperature= 0.3
top_k= 10
top_p= 0.2
do_sample=True

[etl_inbox]
root = /app/rag_doc/inbox
with_embedding = with_embedding
without_embedding = without_embedding
scan_cron_hour = 6
scan_cron_minute = 0

[embedding]
mode = cloud
local_model_path = /app/models/hub/models--BAAI--bge-m3/snapshots/5617a9f61b028005a4858fdac845db406aefb181
min_vram_bytes = 4294967296
min_ram_bytes = 6442450944
cloud_model = text-embedding-3-small

[rag_setting]
enable= True
cloud = True
; hf.co/djuna/jina-embeddings-v2-base-code-Q5_K_M-GGUF:latest
; /mnt/hdd1/Projects/iap/iap_backend/models/hub/models--BAAI--bge-reranker-base/snapshots/2cfc18c9415c912f9d8155881c133215df768a70
; /app/models/hub/models--BAAI--bge-reranker-base/snapshots/2cfc18c9415c912f9d8155881c133215df768a70
rag_model_name = bge-m3:latest
rerank_model=
reranker_top_k = 10
retrivel_top_k = 10
index_dir = /app/db/rag_db
input_dir = /app/rag_doc
folder_path = /app/rag_doc
images_path = /app/db/images
retrive_mode = vector
rag_chunk_size=1024
rag_dim = 1536
rag_start_time = 2024/10/3
rag_end_time = 
rag_index_name = iap
[auth]
login_enable = False

[log_setting]
LOG_PATH = /app/db/logs
